version: '3.7'

services:
  web:
    build: .
    command: bash -c "
      python manage.py db init
      && python manage.py db migrate
      && python manage.py db upgrade
      && python manage.py runserver --host 0.0.0.0"
    volumes:
      - .:/app/
    ports:
      - 5000:5000
    environment:
      - APP_SETTINGS=config.ProductionConfig
      - DATABASE_URL=postgresql://jenkins:jenkins@db:5432/jenkins-viewer
  db:
    image: postgres:12-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=jenkins
      - POSTGRES_PASSWORD=jenkins
      - POSTGRES_DB=jenkins-viewer

volumes:
  postgres_data: